validation: sovereign
version: 1
accounts:
- name: alice
  mnemonic: play butter frown city voyage pupil rabbit wheat thrive mind skate turkey helmet thrive door either differ gate exhibit impose city swallow goat faint
  coins:
  - 20000token
  - 200000000stake
- name: bob
  coins:
  - 10000token
  - 100000000stake
faucet:
  name: bob
  coins:
  - 5token
  - 100000stake
client:
  typescript:
    path: ts-client
  openapi:
    path: docs/static/openapi.yml

genesis:
  consensus:
    params:
      abci:
        vote_extensions_enable_height: "1"
validators:
- name: alice
  bonded: 100000000stake
  app:
    minimum-gas-prices: 0.25stake
    telemetry:
      enabled: true
      global-labels: [ xarchai , xarchai2 ]
      metrics-sink: "100"
      prometheus-retention-time: "2"
